These includes all the changes from Ethan Main
v-sizing/brandnew-rif-vs pull request #5
Opened 2016-10-14 00:59 UTC by Inventorer

The app.yaml is the same one we've all been using.  The main.py is the file we covered on the call today with all the changes Ethan made as well as the changes I made and Eric helped us make on the call.  The sendPost.html is the file Ethan made with a change I made to stringify the JSON and also to include the dictionary changes Eric suggested on the call.

2016-10-14 02:25 UTC, EricHennigan requested changes

2016-10-14 02:25 UTC, EricHennigan commented on main.py
> +class userMorphology(ndb.Model):
nit: all class names should be CapWords

2016-10-14 02:25 UTC, EricHennigan commented on main.py
> +    mPairs = ndb.StructuredProperty(measurePair, repeated=True)
nit: better name is "measurements"

2016-10-14 02:25 UTC, EricHennigan commented on main.py
> +    date = ndb.DateTimeProperty(auto_now_add=True)
blank line to signal the end of a block, before the method that follows.

2016-10-14 02:25 UTC, EricHennigan commented on main.py
> +                                           j['emailID'] or "*notitle*"),
Add a TODO that 'emailID' is a required field. Then, in a later change, we can check and enforce it, sending back a 400 Bad Request code https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

2016-10-14 23:26 UTC, v-size commented on main.py
> +class userMorphology(ndb.Model):
done

2016-10-14 23:27 UTC, v-size commented on main.py
> +    mPairs = ndb.StructuredProperty(measurePair, repeated=True)
I used Measurement (singular) since the class refers to an individual name/value pair.

2016-10-14 23:27 UTC, v-size commented on main.py
> +    date = ndb.DateTimeProperty(auto_now_add=True)
done

2016-10-14 23:28 UTC, v-size commented on main.py
> +                                           j['emailID'] or "*notitle*"),
Added a comment in the code.  Where else should we add the TODO?

2016-10-17 02:50 UTC, EricHennigan commented
This code is obsoleted by pull/6

2016-10-17 02:50 UTC, closed without merging